import type { Metadata } from "next";
import { Abel } from "next/font/google";
import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";

const abel = Abel({
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${abel.className} antialiased`}>{children}</body>
    </html>
  );
}
